### PR TITLE
Update to kernel 5.6

### PR DESCRIPTION
**Pull request by ikegami-t**

### CODE REVIEW

**Comment by Redi007** [comment]
Doesn't work fo rme. I know Ubuntu 20.04 uses the Kernel 5.4 but the 5.6 driver should support it to or am I wrong?

**Comment by xnox** [comment]
@Redi007 20.04 has both v5.4 and v5.6 kernels. Ideally should work with both.

**Comment by ikegami-t** [comment]
> Doesn't work fo rme. I know Ubuntu 20.04 uses the Kernel 5.4 but the 5.6 driver should support it to or am I wrong?

Currently the Kernel v5.7 is used by Ubuntu 20.04 on my local environment.
```
tokunori@tokunori:~$ uname -a
Linux tokunori 5.7.0-rc3+ #1 SMP Wed May 6 16:31:02 JST 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Also confirmed the changes are required from v5.6 from the kernel git log.
By the way I am wondering whether the rtl8812au driver can be imported into the kernel.

**Comment by gordboy** [comment]
I use Ubuntu 20.04 with kernel 5.4 so I really don't know. Chasing new kernel versions just causes headaches, I've found.

Also correcting other peoples' patches is time-consuming. The last time I looked at this it all worked fine with the 5.6 oem kernel, if memory serves well.

**Pull request closed without merging**
